# services:
#   postgres:
#     build: .
#     container_name: postgres
#     image: postgres:15
#     restart: always
#     ports:
#       - '5432:5432'
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - default_network
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_HOST: ${POSTGRES_HOST}
#       POSTGRES_PORT: ${POSTGRES_PORT}

#   pg_admin:
#     container_name: pg_admin
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - '8080:80'
#     networks:
#       - default_network
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

# networks:
#   default_network:
#     driver: bridge

# volumes:
#   pgdata:

version: '3.9'

services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:0.8.0-pg15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
